### PR TITLE
Added the option for a legend

### PR DESCRIPTION
**Pull request by csese**
Forced network can take the argument as an option if one wants to add a legend to the forced graph. 
image

### CODE REVIEW

**Comment by csese** [comment]
In the latest commit, one can specify the radius for the forcedNetwork. 
image

**Comment by christophergandrud** [comment]
Thanks for the pull request. 

I am currently unable to get the legend capability working in the base example, e.g.:

```{S}
data(MisLinks)
data(MisNodes)

# Create graph
forceNetwork(Links = MisLinks, Nodes = MisNodes, Source = "source",
             Target = "target", Value = "value", NodeID = "name",
             Group = "group", opacity = 0.4, legend = T)
```

Does not seem to produce a plot with a legend. 

Could you please fix, document, and resubmit.

**Comment by christophergandrud** [comment]
Could you possibly re-fork the current master, paste in your changes, then resubmit the pull request? 

The current pull request has a ton of extra files and directories. (You may have been making shiny plots or something similar with the package as your working directory, which then added these.)

Thanks

**Comment by csese** [comment]
I have created the new pull request.

**Pull request closed without merging**
