### PR TITLE
 sankeyNetwork: right aline nodes with just 1 sink, highlight all links through node on mouseover

### PR DESCRIPTION
**Pull request by giko45**
add iterations parameter to sankeyNetwork
+ aline nodes with just 1 sink to second right place

### CODE REVIEW

**Comment by christophergandrud** [comment]
Thanks. Can you provide a reproducible example to test this?

**Comment by giko45** [comment]
Hi,

just use the one you have in the documentation and note that some nodes will move to the right. Is a matter of visual taste if you like i better i suppose. For some graphs it will provide a better layout though so maybe it shouldn't be merged back as is.

Regards

# Recreate Bostock Sankey diagram: http://bost.ocks.org/mike/sankey/
# Load energy projection data
URL <- paste0("https://cdn.rawgit.com/christophergandrud/networkD3/",
              "master/JSONdata/energy.json")
Energy <- jsonlite::fromJSON(URL)

# Plot
sankeyNetwork(Links = Energy$links, Nodes = Energy$nodes, Source = "source",
             Target = "target", Value = "value", NodeID = "name",
             units = "TWh", fontSize = 12, nodeWidth = 30,**iterations=200**)

**Comment by giko45** [comment]
added commit link highlighting

**Comment by christophergandrud** [comment]
Thanks. I like the link highlighting.

One last request. Can you write an argument description for `iterations` using `@param` so that it can by roxygen-ized?

**Comment by giko45** [comment]
sure. 
argument description for iterations added.

**Comment by christophergandrud** [comment]
Thanks, the version now up in the pull request seems to not actually implement the iterations argument (changing the value doesn't change the y-position). Could you check this out?

**Comment by giko45** [comment]
Depends on the complexity of the diagram. Test to run with a low value 1 or 2. to see the difference

**Comment by christophergandrud** [comment]
Thanks. Merging now.

**Comment by giko45** [comment]
Thanks

**Pull request merged**
