### PR TITLE
make diagonalNetwork and radialNetwork responsive (sort-of)

### PR DESCRIPTION
**Pull request by timelyportfolio**
This pull is a little more intrusive on the current behavior of `diagonalNetwork` and `radialNetwork`, but I think it wisely lets the [`viewBox`](http://sarasoueidan.com/blog/svg-coordinate-systems/) attribute of `SVG` handle sizing and resizing.  It seems the `resize` method already is a little broken, so I don't think this causes any more damage.  Using this approach also insures that the diagram fits within the `htmlwidget` container `div`, so a `R` user does not need to fiddle with `margins` unless desired.

At a minimum, I think this should exist as an argument to toggle on or off, but I'm very comfortable making this the default behavior especially given @christophergandrud focus on simplicity.
networkd3 responsive

### CODE REVIEW

**Comment by christophergandrud** [comment]
I really like it and don't think there is any need in principle to dedicate an argument to this.

One issue I just spotted and haven't had a chance to look into: If you knit the gh-pages .Rmd file you will see that it produces strange and undesirable behaviour.

**Comment by timelyportfolio** [comment]
Thanks so much for the feedback and bug discovery.  I'll work out the kinks and hopefully have a working pull momentarily.

**Comment by timelyportfolio** [comment]
I believe I have worked out the kinks in 1a9d8f566005c7eb16ef127789e8e23d154874f4.  @christophergandrud, do you mind verifying?

**Comment by christophergandrud** [comment]
Nice, merging into master now.

**Comment by timelyportfolio** [comment]
oh great, what else for CRAN?  anything you would like to implement?  I'll keep going through the existing pulls.

**Comment by christophergandrud** [comment]
Generally, I'm a believer in relatively incremental CRAN updates to mimimise the risk of unanticipated code breaks at any given update. So I'm fine. 

But if you think there is an important pull to merge, then lets do that.

**Comment by timelyportfolio** [comment]
#85 reminded me that the `gh-pages` site will demo the newest and greatest, which argues for a quicker CRAN submit.  I am ready when you are.

**Comment by christophergandrud** [comment]
I'm also ready if you are. I'll make compile it now and send it up to CRAN.

**Comment by christophergandrud** [comment]
. . . submitted v0.2.4

**Pull request merged**
