### PR TITLE
Hierarchical Bundle

### PR DESCRIPTION
**Pull request by pvutov**
At my workplace we created an htmlwidget for bundle graphs based on http://bl.ocks.org/mbostock/7607999. We added some significant customizations to it and some of those won't make sense in a public package, so I'm committing a trimmed-down version.

This is my first attempt at commiting to a formal package, so I'm sure I've missed things.

### CODE REVIEW

**Comment by garthtarr** [comment]
I've also spent a little time implementing a version of hierarchal bundling here: https://github.com/garthtarr/edgebundleR

I'd be happy for any or all of it to be incorporated into networkD3.

**Comment by timelyportfolio** [comment]
@garthtarr happy help integrate if I can

**Comment by timelyportfolio** [comment]
@christophergandrud, would you like to include this in `networkD3`?  It is a very nice diagram.  However, @garthtarr has made `edgebundleR` into quite a nice robust package focused on these diagrams, so I'm not sure a limited implementation in `networkD3` offers much.  Maybe we could reference the package in the documentation for if someone is looking for this functionality.

**Comment by christophergandrud** [comment]
I guess there isn't much point of duplicating capabilities in general. I like the idea of referencing edgbundleR in the documentation.

The only real reason to add it in is if there are substantial syntax differences such that users familiar with networkD3 would benefit from not having to learn a much different api.

**Comment by garthtarr** [comment]
The implementation of edgebundleR is a bit different to networkD3.  I've tried to make edgebundleR as user friendly as possible.  In edgebundleR you can input JSON files, symmetric matrices or igraph objects rather than the networkD3 approach of specifying Links, Nodes, Source, Target,...  This means that it wouldn't be a natural fit with the networkD3 package (though that's still an option if someone wants to do the work to transfer it across!).

If the plan is to reference it in the documentation, I'd be happy to push edgebundleR to CRAN (to make it easier to install for potential users).

**Comment by christophergandrud** [comment]
The reference and CRAN approach seems best to me for the time being.

**Comment by garthtarr** [comment]
FYI edgebundleR is now on CRAN

**Pull request closed without merging**
