### PR TITLE
Added options for legend and radius

### PR DESCRIPTION
**Pull request by csese**
Added parameters in the force network widget for a legend, node radius and node radius calculation.

### CODE REVIEW

**Comment by christophergandrud** [comment]
Thanks. The legend seems to work fine now.

Can you provide an example for `radiusCalculation`?

**Comment by csese** [comment]
I provided an example for both the radiusCalculation and the legend in my latest commit. 
Thanks for doing those modifications.

**Comment by christophergandrud** [comment]
Thanks for your contribution!

**Comment by csese** [comment]
Thank you for your work on this package!

**Pull request merged**
