### PR TITLE
Add a linkstrength option

### PR DESCRIPTION
**Pull request by zachcp**
Add a linkstrength option. This will allow a column in the link dafarame to specify the strength of the link.  I have it wired up so the link strengths gives a separate vector to the JS code, and the linkstrengh() function simply accessed the strength by index in the vector with is the same as the index in the links dataframe.

### CODE REVIEW

**Comment by zachcp** [comment]
in response to  #62

**Comment by zachcp** [comment]
oops. #61

**Comment by christophergandrud** [comment]
Can you add a working example?

**Comment by zachcp** [comment]
here is an example where we would like the intergroup links of the LeMiserables dataset to correspond to the group they are in. I do a little bit of manipulation to determine whether the source and target links are in the same group and then I plot them. There are a fair number of links so the effect is not as striking as with smaller datasets but you can see how the inter-group links form tighter clusters.

```
library(networkD3)
library(dplyr)
data(MisLinks)
data(MisNodes)


mL <- MisLinks
mN <- MisNodes

#add rownumbers
mN <- MisNodes %>% mutate(id = as.numeric(rownames(.))-1) 

#get source group
mL <- merge(mL, mN, by.x="source", by.y="id") %>%
  mutate(sourcegroup=group) %>%
  select(source,target,value,sourcegroup)

#get target group
mL <- merge(mL, mN, by.x="target", by.y="id") %>%
  mutate(targetgroup=group) %>%
  select(source,target,value,sourcegroup, targetgroup)

#add a link strength field
mL <- mL %>% 
  mutate(linkstrength = ifelse(sourcegroup == targetgroup,10, 1)) %>%
  select(source,target,value,linkstrength)

#compare with and without linkstrength field
forceNetwork(Links = mL, Nodes = MisNodes, LinkStrength = "linkstrength",
             Source = "source", Target = "target",
             Value = "value", NodeID = "name",
             Group = "group", opacity = 0.8, charge=-150)

forceNetwork(Links = MisLinks, Nodes = MisNodes, 
             Source = "source", Target = "target",
             Value = "value", NodeID = "name",
             Group = "group", opacity = 0.8, charge=-150)
```

**Comment by christophergandrud** [comment]
Sorry for the late review. 

I can't tell the difference between the two using networkD3 v0.2.7.

**Comment by zachcp** [comment]
thanks for responding. its a been awhile on this side too; I'll take a look in the next few days to verify/correct the behavior.

**Pull request closed without merging**
