### PR TITLE
sankey - cycles, margins, and better sizing/fitting

### PR DESCRIPTION
**Pull request by timelyportfolio**
When I wrote the post to announce `networkD3` version `0.2.4` I realized that I copied the wrong `sankey.js`.  As I was updating the sankey.js plugin, I thought I would add the same better margin argument and `viewBox` responsive fitting/resizing that we added in `0.2.4` for `diagonalNetwork` and `radialNetwork`.

So sorry I messed this up before the CRAN release. @christophergandrud, not sure when would be best to resubmit.  I did the CRAN check locally on Windows 7 with RStudio 3.2.2 and all passed.

### CODE REVIEW

**Comment by timelyportfolio** [comment]
closes #45

**Comment by christophergandrud** [comment]
We could probably do another cran release in the next few days. It has been a few days since the last release so hopefully we won't get Ripley-ed.

**Comment by christophergandrud** [comment]
I just did a few checks and it looks like the v0.2.6 is ready to submit. Does that sound ok?

Also, I want to add you as a primary author on the [package website](https://christophergandrud.github.io/networkD3/). Just let me know if this is ok and, if so, your preferred name and website to link to..

**Comment by timelyportfolio** [comment]
I believe it is ready based on my local CRAN check also.  Normally, I would say let's wait, but I feel like the `sankeyNetwork` is flawed enough that I strongly prefer folks to not have it installed.

That is fine, but certainly not necessary on me as primary author.  Kent Russell and probably a link to http://buildingwidgets.com to promote `htmlwidgets` while we're at it :)

Thanks for working so hard on this.  I believe `networkD3` to be very important to the R/`htmlwidget` ecosystem.

**Comment by christophergandrud** [comment]
Sounds good. I just made the CRAN submission and will update the website now.

**Pull request merged**
