### PR TITLE
Added diagonalNetwork and radialNetwork (rename)

### PR DESCRIPTION
**Pull request by jrowen**
This update re-uses the existing `treeNetwork` code to create a tree with diagonal links via the `diagonalNetwork` function.  If this looks useful, I can add some of the additional params from `dendroNetwork`, but if we're not yet certain of its usefulness, we can go with this implementation for now.  The update also renames `treeNetwork` to `radialNetwork`.

```R
# devtools::install_github("jrowen/networkD3", ref = "diagonal")

Flare <- RCurl::getURL("https://gist.githubusercontent.com/mbostock/4063550/raw/a05a94858375bd0ae023f6950a2b13fac5127637/flare.json")
Flare <- rjson::fromJSON(Flare)

hc <- hclust(dist(USArrests), "ave")

diagonalNetwork(List = Flare, fontSize = 10, opacity = 0.9, margin=0)
diagonalNetwork(as.radialNetwork(hc), height = 700, margin = 50)
```
Let me know if you spot any bugs or have any suggestions.

### CODE REVIEW

**Comment by jrowen** [comment]
We should also add an example(s) to the main page.  When is the source kept?

**Comment by christophergandrud** [comment]
The main page source is just in the gh-pages branch. Update the `.Rmd` file.

**Comment by christophergandrud** [comment]
Looks good. I merge this into master.

**Comment by jrowen** [comment]
In the coming days, I'll work an update to the main page.  Do you want a
separate PR for `dendroNetwork` or one PR for all 3?

**Comment by jrowen** [comment]
It looks like an older version of the `dendroNetwork` PR might have been included in this merge (I'm seeing the squashed commits in the master history).  I'm not sure if you can remove those individual commits.  If not, you may want to reset to the diagonal branch under jrowen/networkD3 and then add your commits from 7/13 and 7/15.  You'll probably need to then force a push.

**Comment by jrowen** [comment]
[This](http://stackoverflow.com/questions/2862590/how-to-replace-master-branch-in-git-entirely-from-another-branch) might help.

**Comment by christophergandrud** [comment]
What is different about the old and the new version of dendroNetwork? It might just be easier to submit a new pull request with the newest version.

**Comment by jrowen** [comment]
The biggest difference is the old version is still using the clusterNetwork
name.

**Comment by jrowen** [comment]
I think you should be able to fix the names by merging the existing
dendroNetwork PR into master.  The commit history will be a bit messy, but
in the end, we should be left with the right code.

**Comment by jrowen** [comment]
I attempted to create a [branch](https://github.com/jrowen/networkD3/tree/cluster2) that merges the dendroNetwork renaming to the current master.  If this is the approach you want to take, let me know and I can create a new PR.

**Comment by christophergandrud** [comment]
That sounds good.

**Pull request merged**
