### PR TITLE
Add support for Chord Diagram

### PR DESCRIPTION
**Pull request by jenniferrogers**
Now users can create beautiful D3 Chord Diagrams to show directed relationships.

### CODE REVIEW

**Comment by christophergandrud** [comment]
That's pretty neat. Thanks for the contribution!

A couple of things I notice that it would be great if you could tidy up:

- For consistency, argument names should follow the `lowerUpper` style

- There appears to be some issue with the labels in the plot. For example `red 15k` overlaps and is kind of illegible. 

- Could you use a cleaner default `color_scale`? The current one is really unwieldy?

- Could you update the NEWS file and bump the version to 0.2.1?

Thanks again!

**Comment by jenniferrogers** [comment]
Sorry we've been slow in fixing these issues. We're currently working on a solution to the labels (it's going to be challenging to display them in a reasonable way regardless of how many categories there are, or how long the labels are). As for the color scale, we tried to use the default D3 colors. If you'd prefer another color scale, though, that would be easy to arrange (we could just make a new one up, or if you had a preference we could use it). Thanks for your prompt feedback, as well.

**Comment by jenniferrogers** [comment]
OK, Marc fixed the labels, so if you let us know whether you'd like the colors changed from the default D3 ones, we can either do that or leave it as is.

**Comment by timelyportfolio** [comment]
Would it be possible to change the name to `chordNetwork` rather than `chordDiagram`, so all functions are `?Network` for consistency?

I plan to review this pull thoroughly and hope to get it integrated before the next CRAN submission.

Thanks so much for the new functionality.

**Comment by jenniferrogers** [comment]
Of course, no problem. Feel free to change the name, or if you'd like I can change it.

**Comment by timelyportfolio** [comment]
@jenniferrogers I merged this in and added you as a contributor. Thanks so much for the contribution.  I think I would like to rework the arguments a bit for better consistency, so you might see some changes over the next couple of days to the API of `chordNetwork`.  Thanks again.

**Comment by timelyportfolio** [comment]
@christophergandrud I hope this is ok to merge in and then iterate.  Let me know if this causes any trouble.

**Comment by timelyportfolio** [comment]
I had forgotten about this `htmlwidget` [chorddiag](https://github.com/mattflor/chorddiag) devoted to these same diagrams.

**Pull request merged**
