### PR TITLE
Added radialNetwork, diagonalNetwork and dendroNetwork examples

### PR DESCRIPTION
**Pull request by jrowen**
Here's a first cut at adding some additional examples for the new/renamed functions.

### CODE REVIEW

**Comment by christophergandrud** [comment]
The text in the `diagonalNetwork` and `radialNetwork` examples is pretty crowded. Could you reformat these so that they are cleaner?

Otherwise, really nice.

**Comment by jrowen** [comment]
I'll take a look.  I might need to find a simpler data set for these examples.

**Comment by jrowen** [comment]
I used a subset of the data for the example diagram.  Let me know what you think.

**Comment by christophergandrud** [comment]
Looks good. Merged

**Pull request merged**
