### PR TITLE
Expose the 'sinksRight' option to sankeyNetwork

### PR DESCRIPTION
**Pull request by fbreitwieser**
sinksRight is already an argument in sankey.js. If TRUE (the default), the last nodes (sinks) are moved on the right border of the plot, otherwise they stay where they are in the sequence. Sometimes this is more appropriate.

This commit exposes the option to the sankeyNetwork function.

### CODE REVIEW

**Comment by christophergandrud** [comment]
Please make sure the pull request passes all checks.

**Comment by fbreitwieser** [comment]
I don't know why that appears. At https://travis-ci.org/christophergandrud/networkD3/requests it says that the build was created successfully. Also local build and check work fine.

**Comment by christophergandrud** [comment]
Thanks, I restarted the build and it cleared the checks. 

One issue though is that I can't tell any difference between when `sinkRight` is true or false.

**Comment by fbreitwieser** [comment]
It does for me. Attached are the screenshots with the two options, networkD3 installed straight from the repo, and a slight modification of the shiny example.

screenshot 2016-05-11 at 19 53 09

screenshot 2016-05-11 at 19 52 51

**Comment by fbreitwieser** [comment]
I'm not sure if that can be the reason, but can you try with a different browser or clear your cache? I remember that I also did not see changes, initially.

**Comment by fbreitwieser** [comment]
I understand now why it worked for me when I did it interactively, but not when you tried it: I put the 
sankey.sinksRight(options.sinksRight) call after the sankey,layout() call in sankeyNetwork.js ... It worked for me because the network preserved the state, but of course not if you call the function only once. Will commit that fix, soon.

**Comment by fbreitwieser** [comment]
sinksRight now works as expected, however the viewBox causes problems zooming in and out in subsequent drawings of the svg. I experienced this previously in a Shiny application where I updated the Sankey network, and it would never display right after the first. Do you have a guess why this happens?

image

**Comment by fbreitwieser** [comment]
I added zomming - though I could put this into a separate pull request. I found the viewport issue was resolved already by @timelyportfolio  in #133 , and my commit probably conflicts with his.

**Comment by christophergandrud** [comment]
That would be great.  Thanks

**Comment by fbreitwieser** [comment]
Ok, zoom's away from this one. Should be ready to merge.

**Comment by timelyportfolio** [comment]
@fbreitwieser thanks for working on this.  do you think you could make this small change also http://stackoverflow.com/questions/22482334/incorrect-output-sankey-diagram-when-using-shiny/39295271#39295271?

**Comment by fbreitwieser** [comment]
I think this is a separate issue, and I'd rather like to have this pull request merged. 

Regarding that linked issue: I'm not sure if the best solution for resolving the Unicode arrow problem is to remove the Unicode. It seems that Shiny works since 2014 with Unicode - maybe the source files aren't encoded in Unicode? I'm not working on Windows machines usually, though.

**Comment by fbreitwieser** [comment]
Is there anything which is not fine with this pull request?

**Comment by christophergandrud** [comment]
Sorry @fbreitwieser I've just been traveling a lot and haven't had a chance to get to this. I'll hopefully have time in the next two or three days.

**Comment by fbreitwieser** [comment]
Thank you @christophergandrud , no problem

**Pull request merged**
