### PR TITLE
Added dendroNetwork

### PR DESCRIPTION
**Pull request by jrowen**
This is a continuation of #60, renaming `clusterNetwork` to `dendroNetwork` and cleaning-up the code.

### CODE REVIEW

**Comment by christophergandrud** [comment]
Can you check the NEWS file to see if this is accurate?

**Comment by jrowen** [comment]
Sorry about that, I updated the NEWS file as well.

**Comment by christophergandrud** [comment]
Thanks. 

Another issue: in RStudio, the output goes to the default browser rather than the RStudio viewer as happens with the other networkD3 functions. It would be great if this was consistent across the new functions as well.

**Comment by jrowen** [comment]
I reused the sizing policy settings for `treeNetwork ` but can remove these settings if they are no longer required.
```R
htmlwidgets::sizingPolicy(viewer.suppress = TRUE,
                                browser.fill = TRUE,
                                browser.padding = 75,
                                knitr.figure = FALSE,
                                knitr.defaultWidth = 800,
                                knitr.defaultHeight = 500)
```

**Comment by jrowen** [comment]
I updated the sizing policy to be consistent with `simpleNetwork` and `forceNetwork`.  It appears that the original settings may have come from `sankeyNetwork`.

**Comment by jrowen** [comment]
To be consistent across the board, would it make sense for me to also update the `sizingPolicy` for `sankeyNetwork`?

**Comment by christophergandrud** [comment]
Sorry about the delay (I was on holiday with no internet access).

Consistency in the `sizingPolicy` sounds good to me.

**Comment by jrowen** [comment]
I updated `sankeyNetwork` to match the others.  I also set `padding = 10`, as some plots, like sankey, were difficult to read with no padding.

Don't forget to also merge #67 when you merge this PR.  

Let me know if you have any additional suggestions.

**Comment by christophergandrud** [comment]
Thanks!

**Pull request merged**
