### PR TITLE
Added clusterTree to create true dendrograms

### PR DESCRIPTION
**Pull request by jrowen**
This PR includes a new function `clusterTree` that leverages the D3 cluster layout to create true dendrograms similar to those available in base R.  Unlike `networkTree`, the node height is specified by `hclust$height`.  The tree can be drawn horizontally or vertically and the links can be diagonal (similar to `networkTree`) or elbow (perpendicular lines, similar to base R).  It is also possible to specify colors for the terminal node text, which is useful in combination with `cutree`.  Zooming is enabled by default, and shiny support is included.  Some examples are below, feedback is welcome.
```
# to install from my fork use
# devtools::install_github("jrowen/networkD3", ref = "cluster")

library(networkD3)
hc <- hclust(dist(USArrests), "ave")

clusterNetwork(hc, height = 600)
clusterNetwork(hc, treeOrientation = "vertical")

clusterNetwork(hc, height = 600, linkType = "diagonal")
clusterNetwork(hc, treeOrientation = "vertical", linkType = "diagonal")

clusterNetwork(hc, textColour = c("red", "green", "orange")[cutree(hc, 3)],
               height = 600)
clusterNetwork(hc, textColour = c("red", "green", "orange")[cutree(hc, 3)],
               treeOrientation = "vertical")
```

### CODE REVIEW

**Comment by christophergandrud** [comment]
Looks neat. Could you build this off of the current master and bump the version to 0.1.9?

**Comment by jrowen** [comment]
I think this should be rebased, but let me know if anything doesn't look right.

**Comment by christophergandrud** [comment]
Rebasing would be perfect.

**Comment by jrowen** [comment]
I rebased and pushed the updates.

**Comment by christophergandrud** [comment]
Looks good. Thanks! 

We should probably rename `treeNetwork` to something like `radialNetwork` and `treeCluster` to something else that is a bit more specific.

**Comment by jrowen** [comment]
Renaming would probably be less confusing.  The `clusterNetwork` is really a dendrogram, so maybe we could incorporate that into the name.

Another option for `treeNetwork` could be to add a param that specifies the type (e.g. radial, diagonal, collapsible, etc).  It is pretty easy to also add the diagonal option to the existing function (similar to [this](http://bl.ocks.org/mbostock/4339083) without the ability to collapse)--this is how I started with the cluster logic.  For ease of use, a `radialNetwork` function could be created that calls `treeNetwork` and sets the param to radial.

**Comment by christophergandrud** [comment]
Potentially I like the idea of having these all called from `tree network`. I'm wondering though if that would lead to argument bloat.

**Comment by jrowen** [comment]
I defiantly think it's best to keep `treeNetwork` and `clusterNetwork` (or whichever name is chosen) as separate functions.  Combining would lead to param bloat and not be very user friendly.  If you want to add to the former's functionality down the road, it might be easier to add a param than to rename to `radialNetwork`, although I do like the idea of a convenience `radialNetwork` function that sets the param for you.

 If you think it makes sense, I can see if I can put together a PR that adds a param to `treeNetwork` allowing a radial or diagonal layout.

**Comment by christophergandrud** [comment]
I would prefer to keep them as separate functions. What about having the
names radialTreeNetwork and diagonalTreeNetwork we could then deprecate
treeNetwork.
On Mon, Jul 13, 2015 at 9:39 AM Jonathan Owen notifications@github.com
<http://mailto:notifications@github.com> wrote:

I defiantly think it's best to keep treeNetwork and clusterNetwork (or
> whichever name is chosen) as separate functions. Combining would lead to
> param bloat and not be very user friendly. If you want to add to the
> former's functionality down the road, it might be easier to add a param
> than to rename to radialNetwork, although I do like the idea of a
> convenience radialNetwork function that sets the param for you.
>
> If you think it makes sense, I can see if I can put together a PR that
> adds a param to treeNetwork allowing a radial or diagonal layout.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christophergandrud/networkD3/pull/60#issuecomment-120930980>
> .
>
​

**Comment by jrowen** [comment]
Sounds like a good plan.  I'll work on a diagonalTreeNetwork PR shortly.

What do you want to call clusterNetwork?  dendroTreeNetwork?
clusterTreeNetwork?  Something else?

**Comment by christophergandrud** [comment]
Do you think `dendroTreeNetwork` is the most descriptive? If so, lets do that.

**Comment by smartinsightsfromdata** [comment]
Apologies for jumping in your discussion.  Dendron in (ancient) Greek means tree.  So it does not sound so good to me.  It would be better dendroNetwork.

**Comment by christophergandrud** [comment]
Thanks @smartinsightsfromdata. networkD3 is written in English so I don't think most users would have been confused, but I like the simplicity of your suggestion: `radialNetwork` and `dendroNetwork`.

**Comment by jrowen** [comment]
I'll work on a rename to `dendroNetwork` and see if I can squash some of
these commits into a cleaner PR.

**Comment by christophergandrud** [comment]
:+1:

**Comment by jrowen** [comment]
This should be renamed to `dendroNetwork` and cleaned-up.  Let me know if you see anything I missed.

**Comment by christophergandrud** [comment]
Are we still renaming `treeNetwork` to `radialNetwork`?

**Comment by jrowen** [comment]
I'm working on another PR for `diagonalNetwork` and can also include a `treeNetwork` -> `radialNetwork` commit.

**Comment by jrowen** [comment]
Portions of this PR were merged as part of #63.  The remaining pieces of this PR are now included in #64.

**Pull request closed without merging**
